Update acanginx-AutoDeployTrigger-85602968-dd3a-43ff-91e4-255de3423e32.yml

diff --git a/.github/workflows/acanginx-AutoDeployTrigger-85602968-dd3a-43ff-91e4-255de3423e32.yml b/.github/workflows/acanginx-AutoDeployTrigger-85602968-dd3a-43ff-91e4-255de3423e32.yml
--- a/.github/workflows/acanginx-AutoDeployTrigger-85602968-dd3a-43ff-91e4-255de3423e32.yml
+++ b/.github/workflows/acanginx-AutoDeployTrigger-85602968-dd3a-43ff-91e4-255de3423e32.yml
@@ -37,12 +37,18 @@ jobs:
           resourceGroup: vimal001
           imageToBuild: aca0001.azurecr.io/acanginx:${{ github.sha }}
           
-      - name: Check container app state
+      - name: Get container apps properties
         run: |
-          az containerapp show --name acanginx --resource-group vimal001 --query instanceView.state
+          output=$(az containerapp show --name acanginx --resource-group vimal001)
+          provisioningState=$(echo $output | jq -r '.properties.provisioningState')
+          runningStatus=$(echo $output | jq -r '.properties.runningStatus')
+          if [ "$provisioningState" != "Succeeded" ] || [ "$runningStatus" != "Running" ]; then
+            echo "Error: Provisioning state is not 'Succeeded' or running status is not 'Running'."
+            exit 1
+          fi
         env:
-          AZURE_SERVICE_PRINCIPAL_USERNAME: ${{ secrets.AZURE_SERVICE_PRINCIPAL_USERNAME }}
-          AZURE_SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }}
+          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
           AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
           
             
