Update acanginx-AutoDeployTrigger-85602968-dd3a-43ff-91e4-255de3423e32.yml

diff --git a/.github/workflows/acanginx-AutoDeployTrigger-85602968-dd3a-43ff-91e4-255de3423e32.yml b/.github/workflows/acanginx-AutoDeployTrigger-85602968-dd3a-43ff-91e4-255de3423e32.yml
--- a/.github/workflows/acanginx-AutoDeployTrigger-85602968-dd3a-43ff-91e4-255de3423e32.yml
+++ b/.github/workflows/acanginx-AutoDeployTrigger-85602968-dd3a-43ff-91e4-255de3423e32.yml
@@ -46,7 +46,7 @@ jobs:
           AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
           AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
 
-      - name: Get revision details
+      - name: Check provisioning state and running status
         run: |
           revision_details=$(az containerapp revision show --name acanginx --resource-group vimal001 --revision "$latest_revision")
           echo "Revision details: $revision_details"
@@ -55,6 +55,22 @@ jobs:
           AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
           AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
           
+      - name: Check Container apps status
+        run: |
+          for i in {1..5}; do
+            output=$(az containerapp show --name acanginx --resource-group vimal001)
+            provisioningState=$(echo $output | jq -r '.properties.provisioningState')
+            runningStatus=$(echo $output | jq -r '.properties.runningStatus')
+            if [ "$provisioningState" = "Succeeded" ] && [ "$runningStatus" = "Running" ]; then
+              echo "Container is running successfully."
+              exit 0
+            else
+              echo "Retry $i: Provisioning state is $provisioningState and running status is $runningStatus."
+              sleep 10  # Wait for 10 seconds before retrying
+            fi
+          done
+          echo "Error: Provisioning state is not 'Succeeded' or running status is not 'Running' after multiple retries."
+          exit 1    
             
 
      
